name: test_on_commit

on:
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_on_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: Lint with golangci-lint
      uses: golangci/golangci-lint-action@v1.33.0
      with:
        args: run --fast --print-issued-lines=false
# test 1.1

