name: master_merged

on:
    pull_request:
        types:
            - closed
        branches:
            - main
jobs:
  master_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Log Deployed!
        run: echo "Deployed!"
#test 1