name: test_on_commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test_on_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test ./...

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.59

# test 1.1


